print("                             Trust Fund Buddy")
print("Total your monthl spending so that your trust fund doesn't run out")
print("<and you're forced to get a real job>.")
print("")
print("please enter the requested, monthly costs. Since yor're rich, ignore pennies and use only dollar amounts")
print("")
print("")

car=int(input("Lamborghini Tune-Ups : "))
rent= int(input("Manhattan Apartment : "))
jet= int(input("Private Jet Rental : " ))
gifts = int(input("Gifts : "))
food = int(input("Dining Out : "))
staff = int(input("Staff (butlers, chef, driver, assistant): "))
guru = int(input("Personal Guru and Coach : "))
games = int(input("Computer Games : "))

print("")
print("Grand total : ",car+rent+jet+gifts+food+staff+guru+games )
